### ISSUE TITLE
vitrual keyboard still pop up at the first time

### ISSUE THREAD

**Issue by mingshi** [acidb/mobiscroll#371] opened 2016-01-15 01:45 UTC
sorry to disturb you
I have got an issue when i use mobiscroll 2.15.1 in my project.
I have initializationed with an input element, however, when i focus the input, the mobiscroll picker view will popup, but, the virtual keyboard will also popup at the first time that visit this page.

I have tried set the input element blur in onBeforeShow function, but it did not work. I also upgrade the mobiscroll version to the latest version, also not work.

so, i get my devide info and browser info to u:

Android version 4.4.2,

browser：navigator.userAgent: Mozilla/5.0 (Linux; U; Android 4.4.2; zh-cn; 4Gå�å�¶æ�º Build/JDQ39) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025488 Mobile Safari/533.1
navigator.appName: Netscape
navigator.appCodeName: Mozilla
navigator.appVersion: 5.0 (Linux; U; Android 4.4.2; zh-cn; 4Gå�å�¶æ�º Build/JDQ39) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025488 Mobile Safari/533.1
navigator.appMinorVersion: undefined
navigator.platform: Linux armv7l
navigator.cookieEnabled: true
navigator.onLine: true
navigator.userLanguage: undefined,

hope to get your help, tanks, best regards

**Comment by dioslaska** [comment] 2016-01-15 07:17
Duplicate of #349

**Closed by dioslaska** 2016-01-15 07:17 UTC
