### ISSUE TITLE
virtual keyboard still pop up if display set to bottom and top

### ISSUE THREAD

**Issue by mrzzcn** [acidb/mobiscroll#349] opened 2015-09-07 05:10 UTC
virtual keyboard still pop up if display set to bottom and top, **only for the first time** ,  set or cancel , then ok.

**Comment by dioslaska** [comment] 2015-09-09 14:15
Can you please specify the exact OS and browser versions on which you're experiencing the issue?
Also, what mobiscroll version are you using?

Thanks

**Comment by mrzzcn** [comment] 2015-09-11 08:03
android,  the wechat app browser.

**Comment by cailihua** [comment] 2016-01-14 01:45
Android version  4.4.2,
browser：navigator.userAgent: Mozilla/5.0 (Linux; U; Android 4.4.2; zh-cn; 4Gåå¶æº Build/JDQ39) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025488 Mobile Safari/533.1
navigator.appName: Netscape
navigator.appCodeName: Mozilla
navigator.appVersion: 5.0 (Linux; U; Android 4.4.2; zh-cn; 4Gåå¶æº Build/JDQ39) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025488 Mobile Safari/533.1
navigator.appMinorVersion: undefined
navigator.platform: Linux armv7l
navigator.cookieEnabled: true
navigator.onLine: true
navigator.userLanguage: undefined,
mobiscroll version 2.15.1

**Comment by dioslaska** [comment] 2016-01-15 07:51
I tested with QQ Browser (https://play.google.com/store/apps/details?id=com.tencent.mtt), version 5.8, and I could not reproduce the issue. 
From the user agent string I see that you're probably using version 5.4, it might be a browser bug.

**Comment by mingshi** [comment] 2016-01-18 02:44
#371 
sorry, we used Mozilla5.0 in android mobile, not QQ Browser.

**Comment by mingshi** [comment] 2016-01-19 02:13
i'm so sorry, we have fixed the issue!
we checked the code, found our programmer used QQ Browser package in android web view module, then we drop the package, the issue fixed!
anyway, thanks for reply

**Comment by wangbagang** [comment] 2016-03-31 01:22
The problem has not fixed by 2.17.1. My browser  is uc-web and wechat。Android version 4.4.2.

**Comment by dioslaska** [comment] 2016-03-31 06:47
Can't reproduce it on UC Browser v10.9.0. Also, where is the wechat browser available, the wechat app in the play store (https://play.google.com/store/apps/details?id=com.tencent.mm) is only a chat app without browsing functionality.

**Comment by wangbagang** [comment] 2016-03-31 07:40
My UC Browser version is 10.9.5.729, I using the browser to open your demo page http://demo.mobiscroll.com/datetime/time/#lang=zh&framework=angular,that's can be reproduced; In QQ brower that's actually no problem. But the inner browser of QQ app  also can be reproduced this problem.

**Comment by wangbagang** [comment] 2016-03-31 07:43
You can send the message 'http://demo.mobiscroll.com/datetime/time/#lang=zh&framework=angular' by wechat app and click the message, then it will be open the page, you can reproduce the problem!

**Comment by unknowfly** [comment] 2016-04-05 08:21
@wangbagang i have the similar issue, try to set the option "display" as popup like "modal" and "bubble", the virtual keyboard does not appear for my case

**Comment by unknowfly** [comment] 2016-04-05 08:22
@wangbagang  i have the similar issue, try to set the option "display" as popup like "modal" and "bubble", the virtual keyboard does not appear for my case

**Comment by unknowfly** [comment] 2016-04-05 08:22
@wangbagang  i have the similar issue, try to set the option "display" as popup like "modal" and "bubble", the virtual keyboard does not appear for my case

**Comment by unknowfly** [comment] 2016-04-05 08:29
@wangbagang  i have the similar issue, try to set the option "display" as popup like "modal" and "bubble", the virtual keyboard does not appear for my case

**Comment by wangbagang** [comment] 2016-04-06 02:44
@dioslaska That's right when I set the option "display" as popup like "modal" and "bubble", but why "bottom" is not work?

**Comment by dioslaska** [comment] 2016-04-06 07:55
The difference which might effect this, is that in top/bottom display mode the popup appears animated.

**Closed** 2023-02-16 07:31 UTC
Labels: core
