### ISSUE TITLE
Conceptual mistake in RTL components

### ISSUE THREAD

**Issue by stehlo** [acidb/mobiscroll#400] opened 2016-10-05 08:45 UTC
Well, I have been waiting with this one, because I knew that you won't be happy about it at all.

This is not a bug. Yet it is a serious conceptual mistake.

Some of the RTL componenents are simply moved from right side to the left side; however, they are not properly mirrored.

For example, the Forms' Switch is still shown with "Off" value on the left side and "On" value on the right side, whilst it should be the other way round.

For users of RTL languages this is very confusing.

And it is not confusing only because it is expected to be the other way round but, very importantly, it is inconsistent with the behaviour of native components of the underlying platforms. Please check the Android native switches. They are all the other way round, i.e. opposite to Mobiscroll's rendering.

I consider this to be an important flaw and, as such, it should be fixed while the version 3.0.0 is still in beta.

Thank you in advance.

**Comment by dioslaska** [comment] 2016-10-05 09:49
Thanks for the report!
If I understand correctly this is a duplicate of #393 

We consider this as a bug, and will be fixed in the upcoming release.

**Closed by dioslaska** 2016-10-05 09:49 UTC
