### ISSUE TITLE
24h view Timeline Zoom BUG

### ISSUE THREAD

**Issue by auauwolff** [acidb/mobiscroll#525] opened 2024-03-07 01:05 UTC
Hello,

I hope this message finds you well.

I wanted to bring to your attention a bug in the timeline component on Zoom, specifically when its type is set to "day."

It appears that adjusting the zoom level of the browser causes the timeline grid to display irregularities in its width, particularly noticeable at certain zoom levels.

To observe this issue firsthand, you can visit the following demo link: (https://demo.mobiscroll.com/fullscreen/timeline/dynamically-color-and-invalidate)

Furthermore, I've attached an image showcasing the anomaly in the UI gridline of the timeline.

![image](https://github.com/acidb/mobiscroll/assets/65273849/811f6037-2437-4499-85e4-fcb6981cf197)

Thank you kindly for looking into this matter.

Warm regards,

**Comment by dioslaska** [comment] 2024-07-03 07:52
This should be fixed with the virtual scroll refactor in 5.31.0. Could not reproduce it anymore on the above demo.

**Closed as completed by dioslaska** 2024-07-03 07:52 UTC
