### ISSUE TITLE
Calendar: Last day of week falls off screen when week numbers are enabled

### ISSUE THREAD

**Issue by JanPeeters** [acidb/mobiscroll#391] opened 2016-09-15 09:13 UTC
With week numbers enabled in the calendar, the last days of the week fall off of the screen on the right side, thus only displaying 6 days of the week. In addition the week labels don't align with the week days anymore.

![2016-09-15_1112](https://cloud.githubusercontent.com/assets/3593990/18544545/640896aa-7b35-11e6-8fff-a9123a290c0b.png)

**Comment by dioslaska** [comment] 2016-09-16 12:37
Thanks for reporting!
It will be fixed in the upcoming beta5 version.

However the week labels not aligning might be caused by some custom CSS you're using (I see that the button styling is different, and there is no border under the days of the week), the alignment seems ok on the demo page: https://demo.mobiscroll.com/v3/javascript/calendar#demo=weekcounter

**Comment by JanPeeters** [comment] 2016-09-16 13:09
Thanks for your answer and I'm glad this will be fixed in the next beta.
About the alignment of the week labels, that was my mistake. I meant the day labels...

**Comment by dioslaska** [comment] 2016-09-22 07:04
Fixed in 3.0.0-beta5

**Closed by dioslaska** 2016-09-22 07:04 UTC
